GET https://api.github.com/repos/udemygptsdk/empty/contents
Content-Type: application/json
X-GitHub-Api-Version: 2022-11-28
Accept: application/vnd.github+json
Authorization: Bearer {{github_token}}



###
