name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  dockerhub:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: andriimz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f docker/hub/Dockerfile -t andriimz/gptsdk-ui:latest .

      - name: Push Docker image
        run: |
          docker push andriimz/gptsdk-ui:latest

#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to DigitalOcean Droplet
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{secrets.HOST}}
#          username: ${{secrets.USERNAME}}
#          key: ${{secrets.KEY}}
#          script: |
#            cd /var/www/gptsdk-ui
#            ssh-agent bash -c 'ssh-add ~/.ssh/gptsdk-ui_rsa; git pull';
#            npm install
#            npm run build
#            ./artisan migrate
#            ./artisan cache:clear
#            echo 'Deployment to digital ocean finished'
